server:
  port: "8080"
  servlet:
    context-path: /diogenes

spring:
  application:
    name: diogenes
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/diogenes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always

  # See:
  # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.security: DEBUG
