server:
  port: "8080"
  servlet:
    context-path: /diogenes
  # Tell tomcat not to cancel large requests on file uploads
  tomcat:
    max-swallow-size: 100MB

spring:
  application:
    name: diogenes
  # Configure database
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/diogenes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # Add colors to console
  output:
    ansi:
      enabled: always
  # Allow uploading larger filers than 1KB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # See:
  # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.security: DEBUG

# Configure the root folder where images will be uploaded. This is read through the
# FileStorageConfig
file:
  # Location in file system:
  uploads-dir: ./uploads
  images-dir: files/items/images
  # API Endpoint path
  images-base-path: ${server.servlet.context-path}/api/v1/files/images/

diogenes:
  # Enable authentication
  security:
    enabled: true

jwt:
  # Secret password used in combination with other parameters to generate JWT
  secret: random-password-todo-reconfigure