name: diogenes-actions (maven)
run-name: Check backend coverage
on:
  push:
    branches:
      - main
jobs:
  check-code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Change directory to spring project 'diogenes'
      run: cd diogenes
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f diogenes/pom.xml
    - name: Run tests and collect coverage
      run: mvn -B test jacoco:report -f diogenes/pom.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}