name: diogenes-actions
run-name: Actions for the diogenes project
on:
  push:
    branches:
      - main
jobs:
  check-code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Change directory to spring project 'diogenes'
      run: cd diogenes
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f diogenes/pom.xml
    - name: Run tests and collect coverage
      run: mvn -B test jacoco:report -f diogenes/pon.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
